language: node_js
node_js:
    - 10
branchs:
    only:
        - master
cache:
    directories:
        - node_modules

install:
    - yarn install

script:
    - yarn test && yarn build

after_script:
    - cd build
    - git init
    - git config user.name "qqqqqcy"
    - git config user.email "qqqqqcy@gmail.com"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
    global:
        - GH_REF: github.com/jdthfe/edm.git
        - secure: 'QDWWIikYFb12Y5NgGkDio8Di1PVBUDtXCvcQGacUglAIOuVfOFJ6IQDDXSWBEKU4KOT2noD3U0qvGevqaJuS0OrDeSJB2vqjaY+fIFTXQ4tQ64OLc5AgFSVmEdEb8oEX2hlaXiyOyUMmAsgm+dPtNdoyG3lXAypbJe31BqXa68pGvfAaOxPRLvy2vxAd+8Zca+fK31m7K99FO/VVU71vETdzxEY5bHqlgtub9UggodU8KeHZH72ilI1KZt1oc/Jz038+qzkgWDsaHLe4IZUqsfSFHEMNp3ZAdxfsaFj5Ez3HL4xpLNbThsIO2lIwpaCuOpxbLFG5ueftN0YPpV7sRKMhQ98Y+0kHCOc4rlpfQdId7mABsh94Wy4z6I/WpdF6pElsXeYo0nbkMZ6dFSM7nDJj56XBpAIzgi4UAR5Mk0mtMzt7/yUSUNSbGzYHgIIG4oWRF7vuJbI3qDbJtsviYCMhRO9bd3QP/Buxs729zByiPcf0Iv3Vm3A8Dm6TACFYIeEQd1XWZN/by8PSL4725HaWRhlbIKgUendQ15iiV92t/QxRFBWX6SlqGScWOnKY1RSpBKB87rTEtkgIqWSuLoP7HbIYtWeOiLS0bWPc5cOKlz4dZ7STtBSHvFofrqmbVC2EJX1ljRTBhzoxAmlcVSMf0+eCvn6rl9gIYFy43DQ='
